### ISSUE TITLE
Making radar data folders

### ISSUE THREAD

**Issue by jrleeman** [Unidata/TdsConfig#64]
http://thredds.ucar.edu/thredds/catalog/nexrad/level3/N0Q/DGX/catalog.html

DGX has no data from recent times - it appears to have been down for awhile. Since there are no data, scripts that look for a URL with a YYYYMMDD in it fail as 404. Can/should we be creating that empty data collection for each day regardless of if data are there?

**Comment by dopplershift** [comment]
Maybe in an ideal world, but all of that is created on-demand by the LDM when data arrive. The only solution I can think of is to add a cron-job to create all these folders, which would also require having a list of all radar sites in this cron-job. IMO, it's not worth the significant effort of writing the script to trade a 404 for an empty page.

That empty page is likely to break scripts anyways since, at least in our current workshop materials, we're just doing `datasets[0]` anyway, which would be out-of-bounds for the empty page.

**Comment by jrleeman** [comment]
Yeah, after talking to @lesserwhirls IRL it seems we should probably be starting at the site level and sort the scans, and get most recent that way. If the site is down for over a month, we should break and consider it inactive so we update the materials.

**Comment by dopplershift** [comment]
If only we add some way to ask, or query, the server for what radar data are available...we could call it the "Radar Query Service."

Oh, wait. :grin: If we're really concerned about the breakage, **that's** the right solution.

**Comment by jrleeman** [comment]
This is in the siphon overview materials for the workshop, not radar specific.
